import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import MobileNavigation from "@/components/shared/MobileNavigation";
import Footer from "@/components/shared/Footer";
import { ToastContainer } from "react-toastify";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Homez || Find Your Next Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${inter.className} h-full antialiased`}
    >
      <body className={`min-h-screen antialiased`}>
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
        <MobileNavigation />
         <ToastContainer />
      </body>
    </html>
  );
}
